// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Analyzes a clothing item image and identifies its characteristics using Gemini AI.
 *
 * - analyzeClothingItem - A function that analyzes the clothing item.
 * - AnalyzeClothingItemInput - The input type for the analyzeClothingItem function.
 * - AnalyzeClothingItemOutput - The return type for the analyzeClothingItem function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeClothingItemInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of a clothing item, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type AnalyzeClothingItemInput = z.infer<typeof AnalyzeClothingItemInputSchema>;

const AnalyzeClothingItemOutputSchema = z.object({
  type: z.string().describe('The type of clothing item (e.g., shirt, dress, pants).'),
  color: z.string().describe('The primary color of the clothing item.'),
  texture: z.string().describe('The texture of the clothing item (e.g., smooth, rough, ribbed).'),
  brand: z.string().optional().describe('The brand of the clothing item, if identifiable.'),
  fit: z.string().describe('The fit of the clothing item (e.g., slim, loose, regular).'),
  season: z.enum(['summer', 'winter', 'spring', 'fall', 'all']).describe('The season for which the clothing item is most suitable.'),
});
export type AnalyzeClothingItemOutput = z.infer<typeof AnalyzeClothingItemOutputSchema>;

export async function analyzeClothingItem(input: AnalyzeClothingItemInput): Promise<AnalyzeClothingItemOutput> {
  return analyzeClothingItemFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeClothingItemPrompt',
  input: {schema: AnalyzeClothingItemInputSchema},
  output: {schema: AnalyzeClothingItemOutputSchema},
  prompt: `You are an AI fashion assistant that analyzes clothing items from images.

  Analyze the following clothing item and identify its characteristics. Use the following information from the image:

  Photo: {{media url=photoDataUri}}

  Provide the characteristics of the clothing item, which are type, color, texture, brand, fit, and season.`,
});

const analyzeClothingItemFlow = ai.defineFlow(
  {
    name: 'analyzeClothingItemFlow',
    inputSchema: AnalyzeClothingItemInputSchema,
    outputSchema: AnalyzeClothingItemOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
