// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A flow for removing the background from an image using AI.
 *
 * - removeBackground - A function that takes an image and returns a version with the background removed.
 * - RemoveBackgroundInput - The input type for the removeBackground function.
 * - RemoveBackgroundOutput - The return type for the removeBackground function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'zod';
import imageSize from 'image-size';

const RemoveBackgroundInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of a clothing item, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type RemoveBackgroundInput = z.infer<typeof RemoveBackgroundInputSchema>;

const RemoveBackgroundOutputSchema = z.object({
  photoUrl: z.string().describe('The image with the background removed, as a public URL.'),
});
export type RemoveBackgroundOutput = z.infer<typeof RemoveBackgroundOutputSchema>;

export async function removeBackground(input: RemoveBackgroundInput): Promise<RemoveBackgroundOutput> {
  return removeBackgroundFlow(input);
}

const removeBackgroundFlow = ai.defineFlow(
  {
    name: 'removeBackgroundFlow',
    inputSchema: RemoveBackgroundInputSchema,
    outputSchema: z.object({ photoDataUri: z.string() }),
  },
  async ({ photoDataUri }) => {
    
    // The user has requested a specific API endpoint, so we are not using the Genkit AI flow for this.
    // The logic has been moved to a server action in `src/app/actions.ts`.
    // This flow is now a placeholder.

    console.warn("removeBackgroundFlow is deprecated. Use the 'removeBackground' server action instead.");

    // To avoid breaking existing code that might still call this, we'll return a placeholder or an error.
    // Returning the original image is a safe fallback.
    return { photoDataUri: photoDataUri };

    // Or throw an error to force migration
    // throw new Error("This Genkit flow is deprecated. Please use the 'removeBackground' server action in 'src/app/actions.ts'.");
  }
);
